import { access, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const iconsRoot = join(here, "../../../icons");
const outFile = join(here, "../src/icons.generated.ts");

const VARIANTS = ["original", "mono"];

async function exists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function validateSvg(name, variant, svg) {
  if (!svg.startsWith("<svg")) {
    throw new Error(`${name}/${variant}.svg must start with <svg`);
  }
  if (!svg.includes("viewBox=")) {
    throw new Error(`${name}/${variant}.svg is missing viewBox`);
  }
}

const entries = await readdir(iconsRoot, { withFileTypes: true });
const iconDirs = entries
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

if (!iconDirs.length) {
  throw new Error(`No icon directories found in ${iconsRoot}`);
}

/** @type {Record<string, object>} */
const icons = {};
const names = new Set();
const aliases = new Set();

for (const dirName of iconDirs) {
  const iconDir = join(iconsRoot, dirName);
  const metadataPath = join(iconDir, "metadata.json");
  const metadata = JSON.parse(await readFile(metadataPath, "utf8"));
  const name = metadata.name ?? dirName;

  if (name !== dirName) {
    throw new Error(
      `${dirName}/metadata.json: name "${name}" must match directory "${dirName}"`,
    );
  }

  if (names.has(name)) {
    throw new Error(`Duplicate icon name: ${name}`);
  }
  names.add(name);

  for (const alias of metadata.aliases ?? []) {
    const key = alias.toLowerCase();
    if (aliases.has(key) || names.has(key)) {
      throw new Error(`${name}: alias "${alias}" conflicts with another icon`);
    }
    aliases.add(key);
  }

  /** @type {Record<string, string>} */
  const variants = {};

  for (const variant of VARIANTS) {
    const svgPath = join(iconDir, `${variant}.svg`);
    if (!(await exists(svgPath))) {
      if (variant === "original") {
        throw new Error(`${name}: missing required original.svg`);
      }
      continue;
    }

    const svg = (await readFile(svgPath, "utf8")).trim();
    validateSvg(name, variant, svg);
    variants[variant] = svg;
  }

  icons[name] = {
    name,
    title: metadata.title,
    category: metadata.category,
    ...(metadata.website ? { website: metadata.website } : {}),
    ...(metadata.aliases?.length ? { aliases: metadata.aliases } : {}),
    variants,
  };
}

const lines = [
  'import type { IconDefinition } from "./types.js";',
  "",
  "/** Generated by scripts/generate-icons.mjs — do not edit. */",
  "",
  `export const icons: Record<string, IconDefinition> = ${JSON.stringify(icons, null, 2)};`,
  "",
];

await writeFile(outFile, lines.join("\n"), "utf8");
console.log(
  `Generated ${Object.keys(icons).length} icon(s) → src/icons.generated.ts`,
);
