import { access, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  assertAliasAvailable,
  assertCanonicalNameAvailable,
  assertIconMetadata,
  assertSvg,
  parseIconCategories,
} from "./validate-icon.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const iconsRoot = join(here, "../../../icons");
const outFile = join(here, "../src/icons.generated.ts");
const categories = parseIconCategories(
  await readFile(join(here, "../src/categories.ts"), "utf8"),
);

const VARIANTS = ["original", "mono"];

async function exists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

const entries = await readdir(iconsRoot, { withFileTypes: true });
const iconDirs = entries
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

if (!iconDirs.length) {
  throw new Error(`No icon directories found in ${iconsRoot}`);
}

/** @type {Record<string, object>} */
const icons = {};
const names = new Set();
const aliases = new Set();

for (const dirName of iconDirs) {
  const iconDir = join(iconsRoot, dirName);
  const metadataPath = join(iconDir, "metadata.json");
  const metadata = JSON.parse(await readFile(metadataPath, "utf8"));
  const meta = assertIconMetadata(dirName, metadata, categories);

  assertCanonicalNameAvailable(meta.name, names, aliases);
  for (const alias of meta.aliases) {
    assertAliasAvailable(meta.name, alias, names, aliases);
  }

  /** @type {Record<string, string>} */
  const variants = {};

  for (const variant of VARIANTS) {
    const svgPath = join(iconDir, `${variant}.svg`);
    if (!(await exists(svgPath))) {
      if (variant === "original") {
        throw new Error(`${meta.name}: missing required original.svg`);
      }
      continue;
    }

    const svg = (await readFile(svgPath, "utf8")).trim();
    assertSvg(`${meta.name}/${variant}.svg`, svg, {
      requireCurrentColor: variant === "mono",
    });
    variants[variant] = svg;
  }

  icons[meta.name] = {
    name: meta.name,
    title: meta.title,
    category: meta.category,
    ...(meta.website ? { website: meta.website } : {}),
    ...(meta.aliases.length ? { aliases: meta.aliases } : {}),
    variants,
  };
}

const lines = [
  'import type { IconDefinition } from "./types.js";',
  "",
  "/** Generated by scripts/generate-icons.mjs — do not edit. */",
  "",
  `export const icons: Record<string, IconDefinition> = ${JSON.stringify(icons, null, 2)};`,
  "",
];

await writeFile(outFile, lines.join("\n"), "utf8");
console.log(
  `Generated ${Object.keys(icons).length} icon(s) → src/icons.generated.ts`,
);
