import type { IconDefinition } from "./types.js";

/** Generated by scripts/generate-icons.ts — do not edit. */

export const icons: Record<string, IconDefinition> = {
  "github": {
    "name": "github",
    "title": "GitHub",
    "category": "platform",
    "website": "https://github.com",
    "aliases": [
      "github-mark"
    ],
    "variants": {
      "original": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\">\n  <path d=\"M12 .5C5.65.5.5 5.65.5 12c0 5.09 3.3 9.41 7.88 10.94.58.11.79-.25.79-.56 0-.27-.01-1.16-.02-2.1-3.2.7-3.88-1.35-3.88-1.35-.53-1.34-1.28-1.7-1.28-1.7-1.05-.72.08-.71.08-.71 1.16.08 1.77 1.19 1.77 1.19 1.03 1.77 2.7 1.26 3.36.96.1-.75.4-1.26.73-1.55-2.55-.29-5.23-1.28-5.23-5.7 0-1.26.45-2.29 1.19-3.1-.12-.29-.52-1.47.11-3.06 0 0 .97-.31 3.18 1.18a11.1 11.1 0 0 1 5.79 0c2.21-1.5 3.18-1.18 3.18-1.18.63 1.59.23 2.77.11 3.06.74.81 1.19 1.84 1.19 3.1 0 4.43-2.69 5.4-5.25 5.69.41.35.78 1.04.78 2.1 0 1.52-.01 2.74-.01 3.11 0 .31.21.68.8.56A11.51 11.51 0 0 0 23.5 12C23.5 5.65 18.35.5 12 .5Z\"/>\n</svg>",
      "mono": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\">\n  <path fill=\"currentColor\" d=\"M12 .5C5.65.5.5 5.65.5 12c0 5.09 3.3 9.41 7.88 10.94.58.11.79-.25.79-.56 0-.27-.01-1.16-.02-2.1-3.2.7-3.88-1.35-3.88-1.35-.53-1.34-1.28-1.7-1.28-1.7-1.05-.72.08-.71.08-.71 1.16.08 1.77 1.19 1.77 1.19 1.03 1.77 2.7 1.26 3.36.96.1-.75.4-1.26.73-1.55-2.55-.29-5.23-1.28-5.23-5.7 0-1.26.45-2.29 1.19-3.1-.12-.29-.52-1.47.11-3.06 0 0 .97-.31 3.18 1.18a11.1 11.1 0 0 1 5.79 0c2.21-1.5 3.18-1.18 3.18-1.18.63 1.59.23 2.77.11 3.06.74.81 1.19 1.84 1.19 3.1 0 4.43-2.69 5.4-5.25 5.69.41.35.78 1.04.78 2.1 0 1.52-.01 2.74-.01 3.11 0 .31.21.68.8.56A11.51 11.51 0 0 0 23.5 12C23.5 5.65 18.35.5 12 .5Z\"/>\n</svg>"
    }
  },
  "nextjs": {
    "name": "nextjs",
    "title": "Next.js",
    "category": "framework",
    "website": "https://nextjs.org",
    "aliases": [
      "next",
      "next.js"
    ],
    "variants": {
      "original": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\">\n  <circle cx=\"12\" cy=\"12\" r=\"11\" fill=\"#000000\"/>\n\n  <path\n    d=\"M7 6.5V17.5H8.8V9.7L15.4 17.5H17V6.5H15.2V14.2L8.7 6.5H7Z\"\n    fill=\"#ffffff\"\n  />\n\n  <path\n    d=\"M13.7 14.2L16.9 17.8H14.7L13.7 16.7V14.2Z\"\n    fill=\"#ffffff\"\n  />\n</svg>",
      "mono": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"currentColor\">\n  <path\n    d=\"M12 1C5.925 1 1 5.925 1 12s4.925 11 11 11 11-4.925 11-11S18.075 1 12 1ZM7 6.5h1.7l6.5 7.7V6.5H17v11h-1.6l-6.6-7.8v7.8H7v-11Zm6.7 7.7 3.2 3.6h-2.2l-1-1.1v-2.5Z\"\n  />\n</svg>"
    }
  },
  "react": {
    "name": "react",
    "title": "React",
    "category": "framework",
    "website": "https://react.dev",
    "aliases": [
      "reactjs"
    ],
    "variants": {
      "original": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\">\n  <circle cx=\"12\" cy=\"12\" r=\"2.2\" fill=\"#61DAFB\"/>\n\n  <g\n    fill=\"none\"\n    stroke=\"#61DAFB\"\n    stroke-width=\"1.25\"\n  >\n    <ellipse cx=\"12\" cy=\"12\" rx=\"10\" ry=\"4.1\"/>\n    <ellipse\n      cx=\"12\"\n      cy=\"12\"\n      rx=\"10\"\n      ry=\"4.1\"\n      transform=\"rotate(60 12 12)\"\n    />\n    <ellipse\n      cx=\"12\"\n      cy=\"12\"\n      rx=\"10\"\n      ry=\"4.1\"\n      transform=\"rotate(120 12 12)\"\n    />\n  </g>\n</svg>",
      "mono": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\">\n  <circle cx=\"12\" cy=\"12\" r=\"2.2\" fill=\"currentColor\"/>\n\n  <g\n    fill=\"none\"\n    stroke=\"currentColor\"\n    stroke-width=\"1.25\"\n  >\n    <ellipse cx=\"12\" cy=\"12\" rx=\"10\" ry=\"4.1\"/>\n    <ellipse\n      cx=\"12\"\n      cy=\"12\"\n      rx=\"10\"\n      ry=\"4.1\"\n      transform=\"rotate(60 12 12)\"\n    />\n    <ellipse\n      cx=\"12\"\n      cy=\"12\"\n      rx=\"10\"\n      ry=\"4.1\"\n      transform=\"rotate(120 12 12)\"\n    />\n  </g>\n</svg>"
    }
  }
};
