import type { IconDefinition } from "./types.js";

/** Generated by scripts/generate-icons.mjs — do not edit. */

export const icons: Record<string, IconDefinition> = {
  "nextjs": {
    "name": "nextjs",
    "title": "Next.js",
    "category": "framework",
    "website": "https://nextjs.org",
    "aliases": [
      "next",
      "next.js"
    ],
    "variants": {
      "original": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\">\n  <circle cx=\"12\" cy=\"12\" r=\"11\" fill=\"#000000\"/>\n\n  <path\n    d=\"M7 6.5V17.5H8.8V9.7L15.4 17.5H17V6.5H15.2V14.2L8.7 6.5H7Z\"\n    fill=\"#ffffff\"\n  />\n\n  <path\n    d=\"M13.7 14.2L16.9 17.8H14.7L13.7 16.7V14.2Z\"\n    fill=\"#ffffff\"\n  />\n</svg>",
      "mono": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"currentColor\">\n  <path\n    d=\"M12 1C5.925 1 1 5.925 1 12s4.925 11 11 11 11-4.925 11-11S18.075 1 12 1ZM7 6.5h1.7l6.5 7.7V6.5H17v11h-1.6l-6.6-7.8v7.8H7v-11Zm6.7 7.7 3.2 3.6h-2.2l-1-1.1v-2.5Z\"\n  />\n</svg>"
    }
  },
  "react": {
    "name": "react",
    "title": "React",
    "category": "framework",
    "website": "https://react.dev",
    "aliases": [
      "reactjs"
    ],
    "variants": {
      "original": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\">\n  <circle cx=\"12\" cy=\"12\" r=\"2.2\" fill=\"#61DAFB\"/>\n\n  <g\n    fill=\"none\"\n    stroke=\"#61DAFB\"\n    stroke-width=\"1.25\"\n  >\n    <ellipse cx=\"12\" cy=\"12\" rx=\"10\" ry=\"4.1\"/>\n    <ellipse\n      cx=\"12\"\n      cy=\"12\"\n      rx=\"10\"\n      ry=\"4.1\"\n      transform=\"rotate(60 12 12)\"\n    />\n    <ellipse\n      cx=\"12\"\n      cy=\"12\"\n      rx=\"10\"\n      ry=\"4.1\"\n      transform=\"rotate(120 12 12)\"\n    />\n  </g>\n</svg>",
      "mono": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\">\n  <circle cx=\"12\" cy=\"12\" r=\"2.2\" fill=\"currentColor\"/>\n\n  <g\n    fill=\"none\"\n    stroke=\"currentColor\"\n    stroke-width=\"1.25\"\n  >\n    <ellipse cx=\"12\" cy=\"12\" rx=\"10\" ry=\"4.1\"/>\n    <ellipse\n      cx=\"12\"\n      cy=\"12\"\n      rx=\"10\"\n      ry=\"4.1\"\n      transform=\"rotate(60 12 12)\"\n    />\n    <ellipse\n      cx=\"12\"\n      cy=\"12\"\n      rx=\"10\"\n      ry=\"4.1\"\n      transform=\"rotate(120 12 12)\"\n    />\n  </g>\n</svg>"
    }
  }
};
